version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: repoteka-postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: repoteka
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: maksonchikw67/repoteka-service:latest
    container_name: repoteka-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: repoteka
      DB_USER: postgres
      DB_PASSWORD: root
    ports:
      - "8000:8000"
    command: ["python3", "-m", "src.cli.main", "serve"]
    restart: unless-stopped

volumes:
  pgdata: